[pkg-upd] 35.2-2 - use gzip as default compression again - kernels under 5.9 don't support zstd

diff --git a/revert-ab6bad7.patch b/revert-ab6bad7.patch
--- a/revert-ab6bad7.patch
+++ b/revert-ab6bad7.patch
@@ -19,6 +19,17 @@
  +
  It's not hard to realize that a filter such as a *tac* or *rev* will cause
  *mkinitcpio* to report success but generate a useless image. Similarly, using a
+--- b/mkinitcpio
++++ a/mkinitcpio
+@@ -856,7 +856,7 @@ if [[ -n "$_optgenimg" ]]; then
+         die "Unable to write to '%s'" "$_optgenimg"
+     fi
+ 
+-    _optcompress="${_optcompress:-"${COMPRESSION:-zstd}"}"
++    _optcompress="${_optcompress:-"${COMPRESSION:-gzip}"}"
+     if ! type -P "$_optcompress" >/dev/null; then
+         warning "Unable to locate compression method: '%s'" "$_optcompress"
+         _optcompress='cat'
 --- b/mkinitcpio.conf
 +++ a/mkinitcpio.conf
 @@ -52,15 +52,15 @@
