[pkg-upd] 36-3
- Actually use gzip

diff --git a/revert-ab6bad7.patch b/revert-ab6bad7.patch
--- a/revert-ab6bad7.patch
+++ b/revert-ab6bad7.patch
@@ -22,6 +22,18 @@ diff --unified --recursive --color a/man/mkinitcpio.conf.5.adoc b/man/mkinitcpio
      an uncompressed image, define this variable as _cat_.
       +
      It is not hard to realize that a filter such as a _tac_ or _rev_ will cause
+--- b/mkinitcpio
++++ a/mkinitcpio
+@@ -856,7 +856,7 @@ if [[ -n "$_optgenimg" ]]; then
+         die "Unable to write to '%s'" "$_optgenimg"
+     fi
+
+-    _optcompress="${_optcompress:-"${COMPRESSION:-zstd}"}"
++    _optcompress="${_optcompress:-"${COMPRESSION:-gzip}"}"
+     if ! type -P "$_optcompress" >/dev/null; then
+         warning "Unable to locate compression method: '%s'" "$_optcompress"
+         _optcompress='cat'
+
 --- b/mkinitcpio.conf
 +++ a/mkinitcpio.conf
 @@ -52,15 +52,15 @@
